version: '3.7'

services:
  web:
    container_name: lunchPickerApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
      
  db:
    container_name: mongo
    image: mongo:4.2
    ports:
      - 27017:27017
    restart: always

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always